<?php

namespace MainBundle\Repository;

/**
 * CheckUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CheckUserRepository extends \Doctrine\ORM\EntityRepository
{
}
