<?php

namespace MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LangageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LangageRepository extends EntityRepository
{
}
